name: Alexander Hultnér Blog – Hultner.se
description: Personal views and reflections.
url: https://hultner.se

theme: minima
exluced: [README.md, CNAME, .gitignore]

footer-links:
    github: hultner
    twitter: ahultner
    linkedin: hultner

